---
- name: installing tomcat
  become: yes
  hosts: all
  tasks:
    - name: update packages and install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
    - name: create a group 
      ansible.builtin.group:
        name: tomcat    
    - name: create an user and add group
      ansible.builtin.user:
        name: tomcat
        create_home: true
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
    - name: get tomcat url
      ansible.builtin.get_url:
        dest: /tmp
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz   
    - name: untar the file
      ansible.builtin.unarchive:         
        src: /tmp/apache-tomcat-9.0.73.tar.gz
        dest: /opt/tomcat
        remote_src: true
    - name: create a symlink
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-9.0.73
        dest:  /opt/tomcat/latest
        owner: tomcat
        group: tomcat
        state: link    