---
- name: installing apache2 php
  become: yes
  hosts: all
  tasks:
    - name: installing apache2 and update
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
    - name: installing php and libapache2-mod-php php-mysql 
      ansible.builtin.apt:
        pkg:
          - php
          - libapache2-mod-php
          - php-mysql
    - name: create a file in /var/www/html/info.php
      ansible.builtin.file:
        path: /var/www/html/info.php
        state: touch
    - name: add content into /var/www/html/info.php
      ansible.builtin.copy:
        dest: /var/www/html/info.php
        content: |
         <?php
         phpinfo();
         ?>
